# Generated by Django 5.1.7 on 2025-03-12 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0002_initial'),
        ('transaction', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='user.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.offer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='user.account'),
        ),
    ]
